### ISSUE TITLE
This is not a issue, its a request :)

### ISSUE THREAD

**Issue by ranjithstar256** [plattysoft/BalloonsGame#1]
Hi Dear Folks,
                      I would like to add a text on the balloons, can you help me?!

**Comment by plattysoft** [comment]
The balloons are images, so you can just edit the images to add text there.
If you want to add dynamic text, that would be a bit more complicated, since you'll need to render it into an image on runtime.
Hope this helps.

**Comment by ranjithstar256** [comment]
Hi thanks for the response. I'll try and let you know. 
Thank you so much 😊
